CREATE TABLE public.status_registro (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(50) NOT NULL,
	abreviacao varchar(1) NOT NULL,
	CONSTRAINT status_registro_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX status_registro_id_idx ON public.status_registro (id);
