CREATE TABLE public.client (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(50) NOT NULL,
	telefone varchar(10) NOT NULL,
	endereco varchar(50) NOT NULL,
	CONSTRAINT client_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX client_id_idx ON public.client (id);
